#!/usr/bin/env ruby

require './src/alegria'
require 'date'
require './src/AV'
require './src/File_Loop'

puts ` echo on 0 | cec-client -s -d 1 ; `.strip
sleep 3

`echo "current process: #{Process.pid}" > /tmp/lobby.tv.process.txt`

minimize_windows
hide_mouse_cursor
auto_git_pull
auto_hide_cursor

HOME_DIR = '/home/pi'.freeze
puts "=== Current directory: #{HOME_DIR}"
puts "=== Date: #{Time.now}"

do_loop = true
reload = false

trap('SIGUSR1') do
  do_loop = false
  reload = true
end

def run_cmd(cmd)
  puts "=== Running: #{cmd}"
  puts `#{cmd}`.strip
end

def update_bg(s_file)
  run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{s_file}")
end

def show_time
  run_cmd %(/apps/alegria/src/time.sign.rb update)
  time_sign = '/tmp/time.sign.svg'
  if File.exist?(time_sign)
    update_bg(time_sign)
    return true
  end

  false
end

class Accidents
  @@last_time = 0
  class << self
    def update
      new_time = File.read('/apps/alegria/data/last.accident.timestamp')
      if new_time != @@last_time
        @@last_time = new_time
        system 'sh/run update accident sign'
        return true
      end
      false
    end

    def show
      update
      run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "/tmp/accident.svg")
    end
  end # class << self
end # def

def hour
  Time.now.strftime('%k').to_i
end

def early_morning?
  hour < 7
end

def shutdown?
  hour > (12 + 4)
end

photo_ext = %( -maxdepth 1 -type f -iname '*.jpg' -or -iname '*.png' -or -iname '*.heic' )
video_ext = %( -maxdepth 1 -type f -iname '*.webm' -or -iname '*.mp4' -or -iname '*.mkv' )
# photos = File_Loop.new(
#   %[find "#{HOME_DIR}/Pictures/\" -maxdepth 1 -type f -iname '*.jpg' -or -iname '*.png' | sort -R --random-source=/dev/urandom]
# )
best_photo = File_Loop.new(%( find "/apps/pictures/best" #{photo_ext} ))
# videos = File_Loop.new(%(find "#{HOME_DIR}/Videos/main" -maxdepth 1 -type f -iname '*.webm' -or -iname '*.mp4'))
exports = File_Loop.new(%(find "/apps/slides/exports" #{photo_ext} | sort -h ))
dept = File_Loop.new(%(find "#{HOME_DIR}/Pictures/dept" #{photo_ext} ))
xmas_party_2023 = File_Loop.new %(find "#{HOME_DIR}/Pictures/xmas_party_2023" #{photo_ext})
india = File_Loop.new %(find "/apps/slides/exports/india_jan2024" #{photo_ext})
# safety_week = File_Loop.new(%(find "#{HOME_DIR}/Videos/safety_week_2024" #{video_ext} ))
# mr_safety = File_Loop.new(%(find "#{HOME_DIR}/Videos/mr_safety" #{video_ext} ))

# Accidents.show
# run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{dept.next}")

AV.volume_to 85
sleep 2

while do_loop
  show_time
  sleep 5

  Accidents.show
  sleep 15

  exports.length.times do |_i|
    run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{exports.next}")
    sleep 30
  end

  show_time
  sleep 5

  india.length.times do |_i|
    run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{india.next}")
    sleep 10
  end

  run_cmd %(sh/play "#{HOME_DIR}/Videos/mark_macross.mp4")

  show_time
  sleep 5

  3.times do |_i|
    run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{xmas_party_2023.next}")
    sleep 5
  end

  show_time
  sleep 5

  run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{dept.next}")
  sleep 7

  run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{best_photo.next}")
  sleep 4

  show_time
  sleep 7

  if shutdown?
    puts ` echo standby 0 | cec-client -s -d 1 ; `.strip
    do_loop = false
    system '/apps/alegria/sh/run pull'
    Accidents.show
    sleep 10
    next
  end

end # while

exec('/apps/alegria/bin/alegria lobby-tv') if repeat

# #!/usr/bin/env ruby
#
# require "./src/alegria"
#
# minimize_windows
# hide_mouse_cursor
#
# auto_reboot
# auto_git_pull
# auto_hide_cursor
#
# while true
#   Alegria.pcmanfm_wallpaper("images/lobby-tv/current.png")
#   sleep_to_min
#   while !on_15th_minute?
#     sleep_to_min
#   end
# end # while
