#!/usr/bin/env ruby
# frozen_string_literal: true

require './src/alegria'
require 'date'
require './src/AV'
require './src/Birthday.Sign'
require './src/File_Loop'

THIS_PID = Process.pid
puts ` echo on 0 | cec-client -s -d 1 ; `.strip
sleep 3

`echo "#{THIS_PID}" > /tmp/lobby.tv.process.txt`

minimize_windows
hide_mouse_cursor
auto_git_pull
auto_hide_cursor

HOME_DIR = '/home/pi'
puts "=== Current directory: #{HOME_DIR}"
puts "=== Date: #{Time.now}"

do_loop = true

RERUN = '/tmp/rerun.txt'
File.delete(RERUN) if File.exist?(RERUN)
trap('SIGUSR1') do
  File.write(RERUN, 'do_it')
  do_loop = false
end

def run_cmd(cmd)
  current_txt = '/tmp/current.txt'
  old_content = File.exist?(current_txt) ? File.read(current_txt) : ''
  line_count = old_content.split("\n").size
  if line_count > 20
    File.write(current_txt, cmd)
  else
    File.write(current_txt, "#{old_content}\n#{cmd}")
  end
  puts "=== Running: #{cmd}"
  puts `#{cmd}`.strip
end

def update_bg(s_file)
  run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{s_file}")
end

def play(s_file)
  run_cmd %(sh/play "#{s_file}")
end

def show_time
  run_cmd %(/apps/alegria/src/time.sign.rb update)
  time_sign = '/tmp/time.sign.svg'
  if File.exist?(time_sign)
    update_bg(time_sign)
    return true
  end

  false
end

class Accidents
  @@last_time = 0
  class << self
    def update
      new_time = File.read('/apps/alegria/data/last.accident.timestamp')
      if new_time != @@last_time
        @@last_time = new_time
        system 'sh/run update accident sign'
        return true
      end
      false
    end

    def show
      update
      run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "/tmp/accident.svg")
    end
  end # class << self
end # class

def hour
  Time.now.strftime('%k').to_i
end

def early_morning?
  hour < 7
end

def shutdown?
  hour > (12 + 4)
end

photo_ext = %( -maxdepth 1 -type f -iname '*.jpg' -or -iname '*.png' -or -iname '*.heic' )
# video_ext = %( -maxdepth 1 -type f -iname '*.webm' -or -iname '*.mp4' -or -iname '*.mkv' )
# photos = File_Loop.new(
#   %[find "#{HOME_DIR}/Pictures/\" -maxdepth 1 -type f -iname '*.jpg' -or -iname '*.png' | sort -R --random-source=/dev/urandom]
# )
# best_photo = File_Loop.new(%( find "/apps/pictures/best" #{photo_ext} ))
videos = File_Loop.new(%(find "#{HOME_DIR}/Videos/main" -maxdepth 1 -type f -iname '*.webm' -or -iname '*.mp4'))
dept = File_Loop.new(%(find "/apps/pictures/teams" #{photo_ext} ))
india = File_Loop.new %(find "/apps/pictures/india_jan2024" #{photo_ext})
flyers = File_Loop.new %(find "/apps/pictures/flyers" #{photo_ext})

xmas_party = File_Loop.new %(find "#{HOME_DIR}/Pictures/xmas_party_2023" #{photo_ext})
# ads    = File_Loop.new %(find "/apps/pictures/ads" #{photo_ext})
# waller = File_Loop.new %(find "/apps/pictures/wall_revival" #{photo_ext})
# forklift = File_Loop.new %(find "/apps/pictures/forklift.safety" #{photo_ext})
# mr_safety = File_Loop.new(%(find "#{HOME_DIR}/Videos/mr_safety" #{video_ext} ))

# Accidents.show
# run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{dept.next}")

AV.volume_to 85
sleep 2

bs_sign = Birthday_Sign.generate

today_month = Birthday_Sign.current_month.downcase
while do_loop

  show_time
  sleep 10

  Accidents.show
  sleep 30

  show_time
  sleep 10

  flyers.length.times do |_i|
    next_f = flyers.next
    case next_f.downcase
    when /birthday.#{today_month}/
      update_bg(bs_sign || next_f)
    else
      update_bg next_f
    end
    sleep 120

    show_time
    sleep 15
  end

  update_bg(bs_sign) if bs_sign

  dept.length.times do |_i|
    update_bg dept.next
    sleep 30

    update_bg xmas_party.next
    sleep 10

    show_time
    sleep 10
  end

  india.length.times do |_i|
    update_bg india.next
    sleep 10
  end

  show_time
  sleep 10

  play videos.next

  next unless shutdown?

  puts ` echo standby 0 | cec-client -s -d 1 ; `.strip
  do_loop = false
  system 'alegria pull'

end # while

#
# minimize_windows
# hide_mouse_cursor
#
# auto_reboot
# auto_git_pull
# auto_hide_cursor
#
