#!/usr/bin/env ruby
# frozen_string_literal: true

require './src/alegria'
require 'date'
require './src/AV'
require './src/File_Loop'

THIS_PID = Process.pid
puts ` echo on 0 | cec-client -s -d 1 ; `.strip
sleep 3

`echo "#{THIS_PID}" > /tmp/lobby.tv.process.txt`

minimize_windows
hide_mouse_cursor
auto_git_pull
auto_hide_cursor

HOME_DIR = '/home/pi'
puts "=== Current directory: #{HOME_DIR}"
puts "=== Date: #{Time.now}"

do_loop = true
reload = false

RERUN = '/tmp/rerun.txt'
File.delete(RERUN) if File.exist?(RERUN)
trap('SIGUSR1') do
  File.write(RERUN, 'do_it')
  do_loop = false
  reload = true
end

def run_cmd(cmd)
  File.write('/tmp/current.txt', cmd)
  puts "=== Running: #{cmd}"
  puts `#{cmd}`.strip
end

def update_bg(s_file)
  run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{s_file}")
end

def play(s_file)
  run_cmd %(sh/play "#{s_file}")
end

def show_time
  run_cmd %(/apps/alegria/src/time.sign.rb update)
  time_sign = '/tmp/time.sign.svg'
  if File.exist?(time_sign)
    update_bg(time_sign)
    return true
  end

  false
end

class Accidents
  @@last_time = 0
  class << self
    def update
      new_time = File.read('/apps/alegria/data/last.accident.timestamp')
      if new_time != @@last_time
        @@last_time = new_time
        system 'sh/run update accident sign'
        return true
      end
      false
    end

    def show
      update
      run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "/tmp/accident.svg")
    end
  end # class << self
end # def

def hour
  Time.now.strftime('%k').to_i
end

def early_morning?
  hour < 7
end

def shutdown?
  hour > (12 + 4)
end

photo_ext = %( -maxdepth 1 -type f -iname '*.jpg' -or -iname '*.png' -or -iname '*.heic' )
video_ext = %( -maxdepth 1 -type f -iname '*.webm' -or -iname '*.mp4' -or -iname '*.mkv' )
# photos = File_Loop.new(
#   %[find "#{HOME_DIR}/Pictures/\" -maxdepth 1 -type f -iname '*.jpg' -or -iname '*.png' | sort -R --random-source=/dev/urandom]
# )
best_photo = File_Loop.new(%( find "/apps/pictures/best" #{photo_ext} ))
# videos = File_Loop.new(%(find "#{HOME_DIR}/Videos/main" -maxdepth 1 -type f -iname '*.webm' -or -iname '*.mp4'))
dept = File_Loop.new(%(find "#{HOME_DIR}/Pictures/dept" #{photo_ext} ))
xmas_party_2023 = File_Loop.new %(find "#{HOME_DIR}/Pictures/xmas_party_2023" #{photo_ext})
india = File_Loop.new %(find "/apps/pictures/india_jan2024" #{photo_ext})
flyers = File_Loop.new %(find "/apps/pictures/flyers" #{photo_ext})
ads    = File_Loop.new %(find "/apps/pictures/ads" #{photo_ext})
waller = File_Loop.new %(find "/apps/pictures/wall_revival" #{photo_ext})
paul_lewis = File_Loop.new %(find "/apps/pictures/paul_lewis" #{photo_ext})
# mr_safety = File_Loop.new(%(find "#{HOME_DIR}/Videos/mr_safety" #{video_ext} ))

# Accidents.show
# run_cmd %(pcmanfm --wallpaper-mode=fit --set-wallpaper "#{dept.next}")

AV.volume_to 85
sleep 2

while do_loop

  show_time
  sleep 10

  Accidents.show
  sleep 30

  play "#{HOME_DIR}/Videos/temp/good.friday.en.mp4"

  show_time
  sleep 10

  play "#{HOME_DIR}/Videos/temp/good.friday.es.mp4"

  show_time
  sleep 10

  flyers.length.times do |_i|
    update_bg flyers.next
    sleep 120
  end

  show_time
  sleep 10

  # india.length.times do |_x|
  #   update_bg india.next
  #   sleep 15
  # end

  # update_bg dept.next
  # sleep 10

  # update_bg xmas_party_2023.next
  # sleep 30
  #
  # update_bg best_photo.next
  # sleep 10

  # waller.length.times do |_i|
  #   update_bg waller.next
  #   sleep 60
  # end

  if shutdown?
    puts ` echo standby 0 | cec-client -s -d 1 ; `.strip
    do_loop = false
    system 'alegria pull'
    Accidents.show
    sleep 10
  end

end
# while

#
# minimize_windows
# hide_mouse_cursor
#
# auto_reboot
# auto_git_pull
# auto_hide_cursor
#
