#!/usr/bin/env zsh

set  -u -e
cd /apps/alegria

sfile="/lib/systemd/system/slideshow.service"
ofile="/apps/alegria/src/lobby-tv/slideshow.service"
if diff "$sfile" "$ofile" ; then
  echo "==== Service already installed" >&2
  batcat "$sfile"
else
  set -x
  sudo apt install zsh ruby git fbi bat
  sudo cp -f -i  "$ofile" "$sfile"
fi
