#!/usr/bin/env zsh
#
#
set -u -e -o pipefail


if ! test "$USER" = "pi" ; then
  set -x
fi

cd $HOME/apps/alegria
mkdir -p tmp

git pull || :

case "$@" in
  "lobby-tv")
    exec src/lobby-tv/main
    ;;
  "vertical-01")
    exec src/vertical-01/main
    ;;
  "menu")
    exec src/menu/main
    ;;
  *)
    echo "!!! Invalid option: $@" >&2
    exit 2
    ;;
esac
