#!/usr/bin/env zsh
#
#
set -u -e -o pipefail


if test "$USER" = "pi" ; then
  cd /home/pi/apps/alegria
else
  cd /apps/alegria
fi



case "$@" in
  -h|--help|help)
    cmd="$0"
    echo "$cmd lobby-tv"
    echo "$cmd pull"
    echo "$cmd reset|update accident sign"
    echo "$cmd write accident UNIX_TIMESTAMP"
    echo "     Updates accident file to today."
    ;;
  "lobby-tv")
    exec src/lobby-tv/main
    ;;
  "vertical-01")
    exec src/vertical-01/main
    ;;
  "menu")
    exec src/menu/main
    ;;
  "pull")
    git pull
    ruby src/accident.sign.rb update
    ;;
  "reset accident sign")
    ruby src/accident.sign.rb reset
    ruby src/accident.sign.rb update
    ;;
  "update accident sign")
    ruby src/accident.sign.rb update
    ;;
  "write accident "*)
    ruby src/accident.sign.rb write "$3"
    ruby src/accident.sign.rb update
    ;;
  *)
    echo "!!! Invalid option: $@" >&2
    exit 2
    ;;
esac
